<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Hotel;
use Faker\Generator as Faker;

$factory->define(Hotel::class, function (Faker $faker) {

    $hotels = [
        'Hotel Royal Reforma',
        'Hotel Metropol',
        'Casa De La Condesa',
        'Bristol Hotel',
        'Hotel Sevilla',
        'Residencia Rochester',
        'Fiesta Inn Naucalpan',
        'Ambassador Mexico',
        'Posada Viena Hotel',
        'Segovia Regency',
        'NH Collection Mexico City Reforma',
        'Hilton Mexico City Airport',
        'Camino Real Aeropuerto Mexico',
        'Barceló México Reforma',
        'Gran Hotel Ciudad de Mexico',
        'Best Western Majestic',
        'Mexico City Marriott Reforma Hotel',
        'Geneve Ciudad De México',
        'Galeria Plaza Reforma',
        'Sheraton Mexico City Maria Isabel Hotel',
        'Four Seasons Hotel Mexico City',
        'Camino Real Polanco Mexico',
        'Hyatt Regency Mexico City',
        'Hotel Century Zona Rosa',
        'Hotel del Ángel',
        'Hotel El Ejecutivo By Reforma Avenue',
        'Del Prado Hotel',
        'Laila Hotel CDMX',
        'Emporio Reforma',
        'Courtyard by Marriott Mexico City Revolucion',
        'Hotel Fontan Reforma',
        'Hotel Regente',
        'Hotel Clé',
        'Hotel Pf',
        'Hotel San Francisco Centro Histórico',
        'Exe Suites San Marino',
        'Hotel Ritz Mexico City',
        'Hotel Suites Amberes',
        'We Hotel Aeropuerto',
        'Isaaya Hotel Boutique By Wtc',
        'Hotel Imperial Reforma',
        'Sevilla Palace Hotel',
        'Fiesta Americana Reforma',
        'Radisson Paraiso Hotel Mexico City',
        'Hotel Marquis Reforma',
        'Hotel Pedregal Palace',
        'Holiday Inn Ciudad De Mexico-Trade Center',
        'Royal Pedregal Hotel',
        'Holiday Inn Mexico Dali Airport',
        'Hotel La Casona',
        'Sheraton Mexico City Santa Fe',
        'JW Marriott Hotel Mexico City',
        'Suites Del Angel',
        'Zocalo Central Mexico City',
        'Habita',
        'Fiesta Inn Periferico Sur',
        'Grand Fiesta Americana Chapultepec',
        'Residencia Polanco',
        'Novotel Mexico City Santa Fe',
        'Eurostars Zona Rosa Suites',
        'Fiesta Inn Insurgentes Viaducto',
        'W Mexico City',
        'Fiesta Inn Centro Historico',
        'Holiday Inn & Suites Mexico Zona Reforma',
        'Condesa Df',
        'Crowne Plaza Hotel DE Mexico',
        'Hotel Marlowe Centro Histórico',
        'Hotel Premier',
        'Hotel Lepanto',
        'City Express Ciudad De Mexico Alameda',
        'Hotel Isabel',
        'Hotel Park Villa',
        'Hotel Roosevelt',
        'Le Méridien Mexico City',
        'Doubletree By Hilton Mexico City Santa Fe',
        'Holiday Inn Express Hotel & Suites Mexico City at The World Trade Center',
        'Corinto Hotel',
        'Camino Real Santa Fe',
        'Hotel & Suites Pf',
        'Camino Real Pedregal Mexico',
        'Suites Contempo',
        'Hippodrome Hotel Condesa',
        'Hotel Del Principado',
        'NH Collection Mexico City Centro Histórico',
        'Holiday Inn Express Mexico Reforma',
        'Boutique Hotel De Cortes',
        'El Diplomatico Hotel',
        'Fiesta Inn Aeropuerto Ciudad de Mexico',
        'Stadia Suites Santa Fe',
        'The Green Park Hotel',
        'Hilton Mexico City Reforma',
        'City Express Ebc Reforma',
        'Holiday Inn Mexico Buenavista',
        'NH Collection Mexico City Santa Fe',
        'Busue A Boutique Experience Hotel',
        'City Suites Anzures',
        'Exe Suites Reforma',
        'Hotel Riazor Aeropuerto',
        'City Express Plus Insurgentes Sur',
        'Hotel Monaco',
    
    ];
    return [
        'name' => $hotels[random_int(0,99)]
    ];
});
